CREATE TABLE watch_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES mls_users(id) ON DELETE CASCADE NOT NULL,
  media_type TEXT NOT NULL,
  title TEXT NOT NULL,
  url TEXT,
  image TEXT,
  season INTEGER,
  episode_number INTEGER,
  episode_name TEXT,
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  date_watched TIMESTAMP NOT NULL,
  recommendation TEXT NOT NULL
);